### ISSUE TITLE
Different file size than the one reported by Vite

### ISSUE THREAD

**Issue by butaca** [alexeychikk/vite-plugin-total-bundle-size#1]
Converting bytes to KB like this

https://github.com/alexeychikk/vite-plugin-total-bundle-size/blob/e6c96b0494414f46e498ed962865340766ffe6ef/src/index.ts#L62

results in a different size than the reported by Vite:

https://github.com/vitejs/vite/blob/69773520f214027070b0ff1a3344394f37ef19f8/packages/vite/src/node/plugins/reporter.ts#L35

**Comment by alexeychikk** [comment]
@butaca  I see there is a debate on wether kB is 1024 or 1000 byte. Since vite went with 1000, I'll stick to that too. Thanks.

**Comment by butaca** [comment]
@alexeychikk that's kind of a philosophical question because at the end if the day is a convention. In some contexts 1024 is used and in others 1000. But since vite is using 1000 and this is a vite plugin, IMO the right choice would be 1000, in order to be consistent with them.

**Comment by alexeychikk** [comment]
@butaca Changed to 1000

**Comment by butaca** [comment]
Thanks!
